#include "SpatialScanCache.h"
#include <yaml-cpp/yaml.h>
#include <iostream>
#include <fstream>

namespace dc
{

juce::File SpatialScanCache::getCacheDir()
{
    return juce::File::getSpecialLocation (juce::File::userApplicationDataDirectory)
               .getChildFile ("DremCanvas")
               .getChildFile ("spatial-cache");
}

juce::File SpatialScanCache::getCacheFile (const juce::String& pluginFileOrIdentifier,
                                           int editorWidth, int editorHeight)
{
    auto key = pluginFileOrIdentifier + ":" + juce::String (editorWidth) + "x" + juce::String (editorHeight);
    auto hash = juce::String::toHexString (key.hashCode64());
    return getCacheDir().getChildFile (hash + ".yaml");
}

void SpatialScanCache::save (const juce::String& pluginFileOrIdentifier,
                             const juce::String& pluginName,
                             int editorWidth, int editorHeight,
                             const std::vector<SpatialParamInfo>& results)
{
    if (results.empty())
        return;

    auto cacheDir = getCacheDir();
    if (! cacheDir.isDirectory())
        cacheDir.createDirectory();

    YAML::Emitter out;
    out << YAML::BeginMap;
    out << YAML::Key << "spatial_scan_cache" << YAML::Value << YAML::BeginMap;
    out << YAML::Key << "plugin_file_or_identifier" << YAML::Value << pluginFileOrIdentifier.toStdString();
    out << YAML::Key << "plugin_name" << YAML::Value << pluginName.toStdString();
    out << YAML::Key << "editor_width" << YAML::Value << editorWidth;
    out << YAML::Key << "editor_height" << YAML::Value << editorHeight;
    out << YAML::Key << "params" << YAML::Value << YAML::BeginSeq;

    for (auto& info : results)
    {
        out << YAML::BeginMap;
        out << YAML::Key << "param_id" << YAML::Value << info.paramId;
        out << YAML::Key << "juce_param_index" << YAML::Value << info.juceParamIndex;
        out << YAML::Key << "center_x" << YAML::Value << info.centerX;
        out << YAML::Key << "center_y" << YAML::Value << info.centerY;
        out << YAML::Key << "hit_count" << YAML::Value << info.hitCount;
        out << YAML::Key << "name" << YAML::Value << info.name;
        out << YAML::EndMap;
    }

    out << YAML::EndSeq;
    out << YAML::EndMap;
    out << YAML::EndMap;

    // Atomic write: write to .tmp then rename
    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);
    auto tmpFile = cacheFile.withFileExtension (".tmp");

    {
        std::ofstream fs (tmpFile.getFullPathName().toStdString());
        if (! fs.is_open())
        {
            std::cerr << "[SpatialScanCache] Failed to open tmp file for writing: "
                      << tmpFile.getFullPathName() << "\n";
            return;
        }
        fs << out.c_str();
    }

    tmpFile.moveFileTo (cacheFile);

    std::cerr << "[SpatialScanCache] Saved " << results.size() << " params to "
              << cacheFile.getFileName() << "\n";
}

bool SpatialScanCache::load (const juce::String& pluginFileOrIdentifier,
                             int editorWidth, int editorHeight,
                             std::vector<SpatialParamInfo>& results)
{
    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);

    if (! cacheFile.existsAsFile())
        return false;

    try
    {
        auto root = YAML::LoadFile (cacheFile.getFullPathName().toStdString());
        auto cache = root["spatial_scan_cache"];
        if (! cache || ! cache.IsMap())
            return false;

        // Validate identifier and dimensions match
        auto storedId = juce::String (cache["plugin_file_or_identifier"].as<std::string>());
        int storedW = cache["editor_width"].as<int>();
        int storedH = cache["editor_height"].as<int>();

        if (storedId != pluginFileOrIdentifier || storedW != editorWidth || storedH != editorHeight)
            return false;

        auto params = cache["params"];
        if (! params || ! params.IsSequence())
            return false;

        results.clear();
        results.reserve (params.size());

        for (auto it = params.begin(); it != params.end(); ++it)
        {
            const auto& node = *it;
            SpatialParamInfo info;
            info.paramId = node["param_id"].as<unsigned int>();
            info.juceParamIndex = node["juce_param_index"].as<int>();
            info.centerX = node["center_x"].as<int>();
            info.centerY = node["center_y"].as<int>();
            info.hitCount = node["hit_count"].as<int>();
            info.name = node["name"].as<std::string>();
            // hintLabel is regenerated by caller
            results.push_back (info);
        }

        std::cerr << "[SpatialScanCache] Loaded " << results.size() << " params from cache\n";
        return ! results.empty();
    }
    catch (const YAML::Exception& e)
    {
        std::cerr << "[SpatialScanCache] Parse error: " << e.what() << "\n";
        return false;
    }
}

void SpatialScanCache::invalidate (const juce::String& pluginFileOrIdentifier,
                                   int editorWidth, int editorHeight)
{
    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);
    if (cacheFile.existsAsFile())
    {
        cacheFile.deleteFile();
        std::cerr << "[SpatialScanCache] Invalidated " << cacheFile.getFileName() << "\n";
    }
}

} // namespace dc
