#include "SpatialScanCache.h"
#include "dc/foundation/file_utils.h"
#include "dc/foundation/string_utils.h"
#include <yaml-cpp/yaml.h>
#include <functional>
#include <iostream>
#include <fstream>

namespace dc
{

namespace fs = std::filesystem;

fs::path SpatialScanCache::getCacheDir()
{
    return getUserAppDataDirectory() / "spatial-cache";
}

fs::path SpatialScanCache::getCacheFile (const std::string& pluginFileOrIdentifier,
                                         int editorWidth, int editorHeight)
{
    auto key = pluginFileOrIdentifier + ":" + std::to_string (editorWidth) + "x" + std::to_string (editorHeight);
    auto hash = dc::format ("%llx", static_cast<unsigned long long> (std::hash<std::string>{} (key)));
    return getCacheDir() / (hash + ".yaml");
}

void SpatialScanCache::save (const std::string& pluginFileOrIdentifier,
                             const std::string& pluginName,
                             int editorWidth, int editorHeight,
                             const std::vector<SpatialParamInfo>& results)
{
    if (results.empty())
        return;

    auto cacheDir = getCacheDir();
    std::error_code ec;
    fs::create_directories (cacheDir, ec);

    YAML::Emitter out;
    out << YAML::BeginMap;
    out << YAML::Key << "spatial_scan_cache" << YAML::Value << YAML::BeginMap;
    out << YAML::Key << "plugin_file_or_identifier" << YAML::Value << pluginFileOrIdentifier;
    out << YAML::Key << "plugin_name" << YAML::Value << pluginName;
    out << YAML::Key << "editor_width" << YAML::Value << editorWidth;
    out << YAML::Key << "editor_height" << YAML::Value << editorHeight;
    out << YAML::Key << "params" << YAML::Value << YAML::BeginSeq;

    for (auto& info : results)
    {
        out << YAML::BeginMap;
        out << YAML::Key << "param_id" << YAML::Value << info.paramId;
        out << YAML::Key << "juce_param_index" << YAML::Value << info.juceParamIndex;
        out << YAML::Key << "center_x" << YAML::Value << info.centerX;
        out << YAML::Key << "center_y" << YAML::Value << info.centerY;
        out << YAML::Key << "hit_count" << YAML::Value << info.hitCount;
        out << YAML::Key << "name" << YAML::Value << info.name;
        out << YAML::EndMap;
    }

    out << YAML::EndSeq;
    out << YAML::EndMap;
    out << YAML::EndMap;

    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);

    if (! writeStringToFile (cacheFile, out.c_str()))
    {
        std::cerr << "[SpatialScanCache] Failed to write cache file: "
                  << cacheFile.string() << "\n";
        return;
    }

    std::cerr << "[SpatialScanCache] Saved " << results.size() << " params to "
              << cacheFile.filename().string() << "\n";
}

bool SpatialScanCache::load (const std::string& pluginFileOrIdentifier,
                             int editorWidth, int editorHeight,
                             std::vector<SpatialParamInfo>& results)
{
    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);

    if (! fs::exists (cacheFile))
        return false;

    try
    {
        auto root = YAML::LoadFile (cacheFile.string());
        auto cache = root["spatial_scan_cache"];
        if (! cache || ! cache.IsMap())
            return false;

        // Validate identifier and dimensions match
        auto storedId = cache["plugin_file_or_identifier"].as<std::string>();
        int storedW = cache["editor_width"].as<int>();
        int storedH = cache["editor_height"].as<int>();

        if (storedId != pluginFileOrIdentifier || storedW != editorWidth || storedH != editorHeight)
            return false;

        auto params = cache["params"];
        if (! params || ! params.IsSequence())
            return false;

        results.clear();
        results.reserve (params.size());

        for (auto it = params.begin(); it != params.end(); ++it)
        {
            const auto& node = *it;
            SpatialParamInfo info;
            info.paramId = node["param_id"].as<unsigned int>();
            info.juceParamIndex = node["juce_param_index"].as<int>();
            info.centerX = node["center_x"].as<int>();
            info.centerY = node["center_y"].as<int>();
            info.hitCount = node["hit_count"].as<int>();
            info.name = node["name"].as<std::string>();
            // hintLabel is regenerated by caller
            results.push_back (info);
        }

        std::cerr << "[SpatialScanCache] Loaded " << results.size() << " params from cache\n";
        return ! results.empty();
    }
    catch (const YAML::Exception& e)
    {
        std::cerr << "[SpatialScanCache] Parse error: " << e.what() << "\n";
        return false;
    }
}

void SpatialScanCache::invalidate (const std::string& pluginFileOrIdentifier,
                                   int editorWidth, int editorHeight)
{
    auto cacheFile = getCacheFile (pluginFileOrIdentifier, editorWidth, editorHeight);
    if (fs::exists (cacheFile))
    {
        std::error_code ec;
        fs::remove (cacheFile, ec);
        std::cerr << "[SpatialScanCache] Invalidated " << cacheFile.filename().string() << "\n";
    }
}

} // namespace dc
